# ==========================================================
#  Este archivo solo hace efecto cuando enciendes la web
#  (Settings -> Pages). Hasta entonces, no molesta.
#
#  Cambia el titulo y la descripcion por los tuyos.
#  Y prueba a cambiar la palabra del tema: cambia todo el aspecto.
#  Otros temas: minima, midnight, architect, slate, hacker, dinky
# ==========================================================
title: TDA Lab de [tu nombre]
description: [tu curso] - Curso 2026-2027
theme: jekyll-theme-cayman
